version: '3'

services:
  reverse-proxy:
    image: traefik:v2.5
    command:
      - '--api.insecure=true'
      - '--providers.docker'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'

    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    labels:
      - 'traefik.http.routers.dashboard.rule=Host(api.nasadax.com) && (PathPrefix(/api) || PathPrefix(/dashboard))'

  api-swagger:
    build: .
    ports:
      - '8000:8000'
    labels:
      - 'traefik.http.routers.api-swagger.rule=Host(api.nasadax.com) && PathPrefix(/api)'
